Repository SCE-Development/SCE-discord-bot, pull requests merged in 2020-10, with the labels that each got.

#84 Verify role is study role
  .gitignore
  src/commands/admin/createStudyChannel.js
  src/commands/admin/deleteStudyChannel.js
  src/commands/member_services/joinStudychannel.js
Labels: bug

#85 Set topic for voice channels
  server.js
  src/VoiceChannelChangeHandler.js
  src/commands/member_services/setvoicetopic.js
Labels: New Command, enhancement

#78 Set up backend / refactor server.js
  .gitignore
  api/models/points.js
  api/resolvers/index.js
  api/resolvers/points.js
  config.example.json
  package-lock.json
  package.json
  server.js
Labels: Database, enhancement
