Repository SCE-Development/SCE-discord-bot, pull requests merged in 2020-04, with the labels that each got.

#16 Arrange command files by category
  package-lock.json
  package.json
  server.js
  src/commands/admin/cct.js
  src/commands/admin/jail.js
  src/commands/member_services/doorcode.js
  src/commands/util/help.js
  src/commands/util/ping.js
  src/commands/util/sid.js
Labels: enhancement

#18 Add generic class for bot commands
  server.js
  src/commandHandler.js
  src/commands/Command.js
  src/commands/admin/cct.js
  src/commands/admin/jail.js
  src/commands/member_services/doorcode.js
  src/commands/util/help.js
  src/commands/util/ping.js
  src/commands/util/sid.js
Labels: enhancement

#20 Command is case insensitive
  server.js
Labels: Commands, enhancement

#21 Add Class to Handle Command and Cooldown
  server.js
  src/CommandHandler.js
  src/commands/Command.js
  src/commands/util/ping.js
  src/commands/util/sid.js
  src/util/CooldownManager.js
  src/util/constants.js
Labels: documentation, enhancement, help wanted

#22 Add Additional ESLint Rules
  .eslintrc.json
  package.json
  server.js
  src/CommandHandler.js
  src/commands/admin/cct.js
  src/commands/util/help.js
  src/util/CooldownManager.js
Labels: enhancement

#23 Create Issue Template for Adding Commands
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: documentation, enhancement

#24 Added instructions on how to use the bot
  README.md
  config.example.json
Labels: documentation

#35 Add Command Parser
  src/CommandHandler.js
  src/util/CommandParser.js
Labels: enhancement

#33 Add Ban Functionality
  src/commands/admin/ban.js
Labels: New Command

#32 Add Kick command
  src/commands/admin/kick.js
  src/commands/util/ping.js
Labels: New Command
