Repository SCE-Development/SCE-discord-bot, pull requests merged in 2020-08, with the labels that each got.

#52 Github Discord Bot Service
  config.example.json
  src/commands/member_services/github.js
  src/util/GithubFetcher.js
  src/util/GithubMessageGenerator.js
Labels: enhancement

#53 Update API URL addresses
  config.example.json
  src/util/GithubFetcher.js
Labels: bug

#48 Updates to README pt.2
  README.md
Labels: documentation
